import React from 'react';
import {render,screen,act,fireEvent,waitFor} from '@testing-library/react';
import RelatedTickerPanel,{checkedCoefficient} from './RelatedTickerPanel';
const pair={symbol:'NVDL',coefficient:0.8,paired_returns:40,requested_returns:90,start_date:'2026-08-01',end_date:'2026-10-06',partial:true,stale:false};
const packet=(ticker='NVDA',overrides={})=>({ticker,window:90,scope:'related',status:'available',products:[{symbol:'NVDL',underlying:'NVDA',issuer:'GraniteShares',daily_target:2,reset:'daily',provider_listed:true,source_urls:['https://graniteshares.com/etfs/']}],coverage:{eligible:5,checked:2,usable:2,pending:3,failed:0,stale:0,partial:2,complete:false,checked_complete:false},positive:[pair],negative:[{...pair,symbol:'NVD',coefficient:-0.9}],comparisons:[pair,{...pair,symbol:'NVD',coefficient:-0.9},{symbol:'WAIT',coefficient:null,paired_returns:0,reason:'missing_history'}],expected_last_close:'2026-10-06',...overrides});
beforeEach(()=>{sessionStorage.clear();global.fetch=jest.fn(async()=>({ok:true,json:async()=>packet()}));});
test('zero stays a measured value while missing and invalid coefficients stay unavailable',()=>{expect(checkedCoefficient({...pair,coefficient:0})).toBe(0);for(const coefficient of [null,true,'0.7',NaN,Infinity,1.2])expect(checkedCoefficient({...pair,coefficient})).toBeNull();expect(checkedCoefficient({...pair,paired_returns:19})).toBeNull();});
test('shows both product links and measured price changes with partial history and unavailable cells',async()=>{render(<RelatedTickerPanel ticker="NVDA"/>);expect(await screen.findAllByText('40 matching days · 2026-08-01 to 2026-10-06 · partial history')).toHaveLength(2);expect(screen.getByText('Linked funds and products')).toBeInTheDocument();expect(screen.getByText('Moves together')).toBeInTheDocument();expect(screen.getByText('Moves opposite')).toBeInTheDocument();expect(screen.getByText(/2 of 5 names checked/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'WAIT —'})).toBeInTheDocument();expect(global.fetch.mock.calls.every(([,options])=>!options.method)).toBe(true);});
test('late replies from a previous stock cannot become the new stocks comparisons',async()=>{let old;global.fetch=jest.fn(url=>String(url).includes('/SPY?')?new Promise(resolve=>{old=resolve;}):Promise.resolve({ok:true,json:async()=>packet('NVDA')}));const view=render(<RelatedTickerPanel ticker="SPY"/>);view.rerender(<RelatedTickerPanel ticker="NVDA"/>);await screen.findByText(/2 of 5 names checked/);await act(async()=>old({ok:true,json:async()=>packet('SPY',{products:[{symbol:'OLD',issuer:'Old',provider_listed:true,source_urls:[]}]})}));expect(screen.queryByRole('button',{name:'OLD'})).toBeNull();expect(screen.getByRole('heading',{name:'NVDA'})).toBeInTheDocument();});
test('closed panel aborts the current comparison read and does not start another batch',async()=>{let warm;global.fetch=jest.fn((url,options)=>options.method==='POST'?new Promise(resolve=>{warm=resolve;}):Promise.resolve({ok:true,json:async()=>packet()}));const view=render(<RelatedTickerPanel ticker="NVDA"/>);await screen.findByText(/2 of 5 names checked/);fireEvent.click(screen.getByRole('button',{name:'Check related products'}));await waitFor(()=>expect(warm).toBeDefined());const signal=global.fetch.mock.calls.find(([,options])=>options.method==='POST')[1].signal;view.unmount();expect(signal.aborted).toBe(true);await act(async()=>warm({ok:true,json:async()=>packet('NVDA',{batch:{done:false}})}));expect(global.fetch.mock.calls.filter(([,options])=>options.method==='POST')).toHaveLength(1);});
test('StrictMode still admits the current comparison after rehearsal cleanup',async()=>{render(<React.StrictMode><RelatedTickerPanel ticker="NVDA"/></React.StrictMode>);await screen.findByText(/2 of 5 names checked/);expect(screen.getByRole('button',{name:'Check related products'})).toBeEnabled();});

test('stops checking when saved price storage is unavailable',async()=>{jest.useFakeTimers();global.fetch=jest.fn(async(url,options)=>({ok:true,json:async()=>packet('NVDA',options.method==='POST'?{status:'unavailable',reason:'cache_storage_unavailable',positive:[],negative:[],comparisons:[],batch:{done:false,attempted:0,reason:'cache_storage_unavailable'}}:{})}));render(<RelatedTickerPanel ticker="NVDA"/>);await act(async()=>{});fireEvent.click(screen.getByRole('button',{name:'Check related products'}));await act(async()=>{});expect(screen.getByText('Saved price storage is unavailable. Checking stopped. Earlier checked comparisons remain shown.')).toBeInTheDocument();await act(async()=>jest.advanceTimersByTime(5000));expect(global.fetch.mock.calls.filter(([,options])=>options.method==='POST')).toHaveLength(1);expect(screen.getByRole('button',{name:'Check related products'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'WAIT —'})).toBeInTheDocument();jest.useRealTimers();});
