import React from 'react';
import {render,screen,fireEvent,waitFor,act} from '@testing-library/react';
import AgentProvider,{useAgent} from './AgentProvider';
import AgentPanelAnswer from './AgentPanelAnswer';
import {publishScreenContext} from './useScreenContext';
function Controls(){const a=useAgent();return <><input aria-label='draft' value={a.question} onChange={e=>a.setQuestion(e.target.value)}/><button onClick={()=>a.askQuestion(a.question)}>Send</button><span data-testid='status'>{a.state}</span><span data-testid='error'>{a.error}</span><AgentPanelAnswer turn={a.activeTurn}/></>;}
beforeAll(()=>Object.defineProperty(globalThis,'crypto',{value:require('crypto').webcrypto,configurable:true}));
beforeEach(()=>{publishScreenContext({page:'heatseeker',ticker:'SPY'});global.fetch=jest.fn(async url=>({ok:true,json:async()=>String(url).includes('/market/catalog')?{instruments:[{symbol:'NVDA'}],has_more:false}:{turn_id:'one',status:'completed',ticker:'SPY',text:'reading'}}));});
const submit=text=>{fireEvent.change(screen.getByLabelText('draft'),{target:{value:text}});fireEvent.click(screen.getByText('Send'));};
test('explicit chart navigation checks ticker and opens without research or model calls',async()=>{const nav=jest.fn(),focus=jest.fn();window.addEventListener('floww:focus-ticker',focus);render(<AgentProvider onNavigate={nav}><Controls/></AgentProvider>);submit('Open NVDA chart');await waitFor(()=>expect(nav).toHaveBeenCalledWith('heatseeker'));expect(focus.mock.calls[0][0].detail).toEqual({ticker:'NVDA'});expect(global.fetch).toHaveBeenCalledTimes(1);expect(global.fetch.mock.calls[0][0]).toContain('/market/catalog?');expect(screen.getByText('Opened Stock chart for NVDA.')).toBeInTheDocument();expect(screen.getByLabelText('draft')).toHaveValue('');expect(screen.queryByText('Saved answer')).toBeNull();window.removeEventListener('floww:focus-ticker',focus);});
test('navigation to screener needs neither selected stock nor research session',async()=>{publishScreenContext({page:'unknown',ticker:null});const nav=jest.fn();render(<AgentProvider onNavigate={nav}><Controls/></AgentProvider>);submit('Open screener');await waitFor(()=>expect(nav).toHaveBeenCalledWith('flowseeker-pro'));expect(global.fetch).not.toHaveBeenCalled();});
test('unconfirmed stock leaves navigation and draft intact',async()=>{global.fetch.mockResolvedValue({ok:true,json:async()=>({instruments:[{symbol:'NVDAX'}],complete_provider_catalog:true,stale:false,has_more:false})});const nav=jest.fn();render(<AgentProvider onNavigate={nav}><Controls/></AgentProvider>);submit('Open NVDA chart');await waitFor(()=>expect(screen.getByTestId('error')).toHaveTextContent('not in'));expect(nav).not.toHaveBeenCalled();expect(screen.getByLabelText('draft')).toHaveValue('Open NVDA chart');});
test('later draft survives a slow navigation response',async()=>{let done;global.fetch.mockReturnValue(new Promise(r=>done=r));const nav=jest.fn();render(<AgentProvider onNavigate={nav}><Controls/></AgentProvider>);submit('Open NVDA chart');fireEvent.change(screen.getByLabelText('draft'),{target:{value:'Explain the chart'}});await act(async()=>done({ok:true,json:async()=>({instruments:[{symbol:'NVDA'}]})}));await waitFor(()=>expect(nav).toHaveBeenCalled());expect(screen.getByLabelText('draft')).toHaveValue('Explain the chart');});

test('whole-market question can start without a stock and keeps explicit market scope',async()=>{publishScreenContext({page:'unknown',ticker:null});const nav=jest.fn();render(<AgentProvider onNavigate={nav}><Controls/></AgentProvider>);submit('Find unusual activity across all stocks');await waitFor(()=>expect(global.fetch.mock.calls.some(([url])=>String(url).endsWith('/ask'))).toBe(true));const call=global.fetch.mock.calls.find(([url])=>String(url).endsWith('/ask'));const body=JSON.parse(call[1].body);expect(body.scope).toBe('market');expect(body.ticker).toBeNull();expect(body.screen.ticker).toBeNull();expect(nav).not.toHaveBeenCalled();});

test('opening the chart without a name follows the screener selected stock',async()=>{publishScreenContext({page:'flowseeker-pro',ticker:'NVDA'});const nav=jest.fn(),focus=jest.fn();window.addEventListener('floww:focus-ticker',focus);render(<AgentProvider onNavigate={nav}><Controls/></AgentProvider>);submit('Find me the chart');await waitFor(()=>expect(nav).toHaveBeenCalledWith('heatseeker'));expect(focus.mock.calls[0][0].detail).toEqual({ticker:'NVDA'});window.removeEventListener('floww:focus-ticker',focus);});
